import type { WorkItem } from "../types";

/**
 * 작업 항목 레지스트리 — DAG (비순환 보장).
 * 완료된 화면 구현(W01~W09) + 향후 백엔드·품질 작업(W10~W16).
 * dependsOn = 선행 id, screens = 건드리는 화면 키(`plane/slug`).
 */
export const WORK_ITEMS: WorkItem[] = [
  {
    id: "W01",
    title: "디자인 시스템 토큰(VDS)",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: [],
    screens: [],
    doc: "src/app/globals.css",
  },
  {
    id: "W02",
    title: "랜딩 페이지 구현",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["learner/landing"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W03",
    title: "레슨 플레이어·OX 퀴즈",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["learner/lesson"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W04",
    title: "용어 사전",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["learner/dictionary"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W05",
    title: "스탬프 맵 UI",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["learner/stamp-map"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W06",
    title: "로그인·회원가입 UI",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["learner/auth"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W07",
    title: "교사용 자료 화면",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["operator/teacher-kit"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W08",
    title: "관리자 대시보드 UI",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["operator/admin-dashboard"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W09",
    title: "404·시스템 상태",
    phase: "P0 디자인·프로토타입",
    status: "done",
    dependsOn: ["W01"],
    screens: ["system/not-found"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W10",
    title: "인증 백엔드(Kakao OAuth)",
    phase: "P1 백엔드·영속화",
    status: "todo",
    dependsOn: ["W06"],
    screens: ["learner/auth", "operator/admin-dashboard"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W11",
    title: "학습 진척 영속화",
    phase: "P1 백엔드·영속화",
    status: "todo",
    dependsOn: ["W10", "W03", "W05"],
    screens: ["learner/lesson", "learner/stamp-map"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W12",
    title: "관리자 인증·역할 게이트",
    phase: "P1 백엔드·영속화",
    status: "todo",
    dependsOn: ["W10"],
    screens: ["operator/admin-dashboard"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W13",
    title: "PDF 다운로드 백엔드",
    phase: "P1 백엔드·영속화",
    status: "todo",
    dependsOn: ["W07"],
    screens: ["operator/teacher-kit"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W14",
    title: "콘텐츠 CMS 연동",
    phase: "P1 백엔드·영속화",
    status: "todo",
    dependsOn: ["W08"],
    screens: ["operator/admin-dashboard"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W15",
    title: "접근성 감사·보강",
    phase: "P2 품질·운영",
    status: "todo",
    dependsOn: ["W02", "W03"],
    screens: ["learner/landing", "learner/lesson"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
  {
    id: "W16",
    title: "관측성·계측 도입",
    phase: "P2 품질·운영",
    status: "todo",
    dependsOn: ["W10"],
    screens: ["learner/landing", "learner/lesson", "operator/teacher-kit"],
    doc: "PLAYBOARD_BUILD_PLAN.md",
  },
];

export const getWorkItem = (id: string): WorkItem | undefined =>
  WORK_ITEMS.find((w) => w.id === id);
